Importing Numpy

In [1]:
import numpy as np

Greating a 1D array

In [2]:
x = [1,2,3,4,5,6]
y = np.array(x)
print(x)
print(y)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [3]:
print(type(x))
print(type(y))

<class 'list'>
<class 'numpy.ndarray'>


Create a null array of size 10

In [4]:

Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Create a null array of size 10 but the fifth value which is 1 

In [5]:

Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Reverse a vector (first element becomes last)

In [6]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Create a 3x3x3 array with random values 

In [8]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.41707152 0.79186847 0.29251606]
  [0.91126807 0.16032974 0.74679249]
  [0.41074168 0.15704354 0.16003776]]

 [[0.41898936 0.84754513 0.79035559]
  [0.69088641 0.91940888 0.91405157]
  [0.40315572 0.18038461 0.95049561]]

 [[0.96272315 0.89163675 0.5606405 ]
  [0.0244208  0.9411901  0.01853869]
  [0.79862969 0.66984417 0.99022298]]]


Indexing Array

In [9]:
my_array = np.array([2,3,4,56,7])
print(my_array[2])


4


Creating a 2D array

In [10]:
array = np.array([(1,2,3),(4,5,6)])
print(array)

[[1 2 3]
 [4 5 6]]


Get 5 and 6 from the above array

In [11]:
print(array[1:,1:])

[[5 6]]


How to check shape of an array

In [12]:
 np.shape(array)

(2, 3)

Pandas 

In [ ]:
import pandas as pd